//
//  NSObject+Constant.h
//  AccuraOCR
//
//  Created by Technozer on 17/02/21.
//  Copyright © 2021 Technozer. All rights reserved.
//

#import <Foundation/Foundation.h>


@interface Constant: NSObject
    
FOUNDATION_EXPORT NSString *const ACCURA_ERROR_CODE_MOTION;
FOUNDATION_EXPORT NSString *const ACCURA_ERROR_CODE_DOCUMENT_IN_FRAME;
FOUNDATION_EXPORT NSString *const ACCURA_ERROR_CODE_BRING_DOCUMENT_IN_FRAME;
FOUNDATION_EXPORT NSString *const ACCURA_ERROR_CODE_PROCESSING;
FOUNDATION_EXPORT NSString *const ACCURA_ERROR_CODE_BLUR_DOCUMENT;
FOUNDATION_EXPORT NSString *const ACCURA_ERROR_CODE_FACE_BLUR;
FOUNDATION_EXPORT NSString *const ACCURA_ERROR_CODE_GLARE_DOCUMENT;
FOUNDATION_EXPORT NSString *const ACCURA_ERROR_CODE_HOLOGRAM;
FOUNDATION_EXPORT NSString *const ACCURA_ERROR_CODE_DARK_DOCUMENT;
FOUNDATION_EXPORT NSString *const ACCURA_ERROR_CODE_PHOTO_COPY_DOCUMENT;
FOUNDATION_EXPORT NSString *const ACCURA_ERROR_CODE_FACE;
FOUNDATION_EXPORT NSString *const ACCURA_ERROR_CODE_MRZ;
FOUNDATION_EXPORT NSString *const ACCURA_ERROR_CODE_PASSPORT_MRZ;
FOUNDATION_EXPORT NSString *const ACCURA_ERROR_CODE_ID_MRZ;
FOUNDATION_EXPORT NSString *const ACCURA_ERROR_CODE_VISA_MRZ;
FOUNDATION_EXPORT NSString *const ACCURA_ERROR_CODE_UPSIDE_DOWN_SIDE;
FOUNDATION_EXPORT NSString *const ACCURA_ERROR_CODE_WRONG_SIDE;
@end


